/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"

*/
public class FindTheDifference
{
    public char FindTheDifferenceCal(string s, string t) {
        char c = ' ';
        for(int i = 0; i < s.Length; i++){
            c ^= s[i];
        }
        for(int i = 0; i < t.Length; i++){
            c ^= t[i];
        }
        return char.ToLower(c);
    }
}